/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hotelproject;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void testAppHasAGreeting() {
        HotelProject classUnderTest = new HotelProject();
        // assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}
